version: '3.9'

services:
  redis:
    image: redis:latest
    container_name: redisserver
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  app:
    build: .
    container_name: flaskapp
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

volumes:
  redis-data:


